# Blueprint Spec version
# (isteğe bağlı, ancak iyi bir pratik olabilir)
# version: 1

services:
  - type: web
    name: backend
    env: node
    plan: free
    region: frankfurt
    buildCommand: "cd server && npm install"
    startCommand: "cd server && npm start"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production

  - type: static_site # Tekrar services altına alıp bu tipi deniyoruz
    name: frontend
    plan: free
    region: frankfurt
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: "./client/build"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    # envVars:
    #   - key: REACT_APP_BACKEND_URL
    #     fromService:
    #       type: web
    #       name: backend
    #       property: url
