services:
  - type: web
    name: backend
    env: node
    plan: free # Veya projenizin ihtiyacına göre bir plan seçin
    region: frankfurt # Size en yakın bölgeyi seçin
    buildCommand: "cd server && npm install"
    startCommand: "cd server && npm start"
    healthCheckPath: "/health"
    envVars:
      - key: NODE_ENV
        value: production
      # Gerekirse buraya başka ortam değişkenleri ekleyebilirsiniz (PORT vb.)

  - type: static
    name: frontend
    plan: free
    region: frankfurt
    buildCommand: "cd client && npm install && npm run build"
    staticPublishPath: "./client/build"
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: NODE_ENV
        value: production
      # Frontend için build zamanında kullanılacak ortam değişkenleri buraya eklenebilir.
      # Örneğin, API endpoint'i REACT_APP_API_URL gibi.
      # Bu değişkenleri client/package.json build script'inde veya
      # client kodunda process.env.REACT_APP_API_URL olarak kullanabilirsiniz. 